package com.example.acar.ordersHistory

import androidx.lifecycle.ViewModel
import com.google.android.gms.maps.model.LatLng
import com.google.android.gms.maps.model.MarkerOptions

class HistoryViewModel : ViewModel() {

    var latLngs1 = listOf<LatLng>(LatLng(50.06465000000001, 19.94498), LatLng(50.06559000000001, 19.94216),
        LatLng(50.06570000000001, 19.941830000000003), LatLng(50.06712, 19.94283), LatLng(50.067260000000005, 19.942860000000003),
        LatLng(50.06727, 19.94509), LatLng(50.06758000000001, 19.94519))

    var pickupmarker = MarkerOptions().position(LatLng(50.06465000000001, 19.94498))
    var destmarker = MarkerOptions().position(LatLng(50.06758000000001, 19.94519))
    var markers1 = listOf<MarkerOptions>(pickupmarker, destmarker)
//
//    var ride1 = RideHistoryItem("12.12.2222", "Katowice", "Krakow", "agqpHcovxB{DrPU`A{GgE[EA}L}@Sq@AeE@wJl@oLlAqCd@k@l@KjBzAlC`@nBo@`MkAlOGrCBn@sAjAS^CRA\\c@?WIcA~Jk@~ECVy@jIW@eDpAiD~BuPxPaDpAgAlAoA?]Aq@Ra@d@}CjDmBvBqBxBcCzBkG|@kBJg@@EPOj@uAxG]j@_E`BeC|AcCpBkAv@]NBZz@zH`B~Kf@zHId\\DlU~@xNzCf]nCn[h@`Le@|Ho@bDyFfSeB~GmC~HkJzXcH~MmEpHiJfSuFhN}AdBgGdEoBtAeC`DsBjDsA`FiAfFq@bDeBvHcElRoK~`@a@nBg@zFmCf^a@zG?vDv@tN^~BbAxBfEbCpB|AlDfFjGfL`C`FpBnFbFnPpGlTzFvPrCfHrHdPbOtW~P`ZpHjPlA~CjD|JfE|NlCdLrCbOdBnLtBjTdDv`@rBjX`Eli@fC|]tAlVn@j]Aha@?pWPxLbApS`CzTxGt^zEjZhAdMbA|VBxNOvKm@hOmAfNqAdKkBrKqCxLuBbHuJ`Wut@fgB_JdUcFvNuFjTkDfR{BfQuBnZo@dY@|Mj@vTx@pPhBv\\nElx@`Bv[x@|[C~PSnKoAd\\q@zZJpUlAtXlC|Y`G|f@bCn\\VtGd@|_@W~UWlIcBxXiDhZcChOeEzR_J`[uExNyHzWcIp_@w@lE}Gvg@eF`b@yGti@aLt~@{EhYiHxZwDjMuEjM}K~ViRt]mu@frAaf@zz@uIjOcKxRyFpMaHpRmF|Q{FhWi\\tkBgZheBiHld@cCzTqBpYcBng@{Bjx@aHleC{@v[[bYBrXh@l\\tB~d@bD~b@~SxkC`Bt[dAle@?pd@[nSmAp_@wCn~@kB~l@o@|d@i@d_BUjc@[jMs@fN}AzQsCnS_DhPaDzLmCpIgE~K{IxQwNrV_b@~r@s~@f}AwSt]kIhMwMnPmGrGsMjKuMjIuL~FsShJ_KbEiG|CcCfBiJpH_HrHeHdKuEtIeF`MyD|LkDdOuBfMuEl\\mD`WcE`ZwN~dAcQroAwEh_@_Dp[gBrX_Dhk@uBf^sChXgBnLiD~PeG~X{UhgA}Lxk@mK`f@eCvGqDzH{F`IkCbCyIbGwEjCoDpCuExFeDzF}D|HcG~HkG|HkB|CmBfB]^yFnAmMjD{MjDqL~CiCh@kBDyLsAmFGmFv@eEhBqF`DaDbAwBAeB[oAi@gC}B_@kBHk@b@e@p@PxAfC|@hE|AnJd@nFPlESzPa@~E_@nMi@zN]jNa@nEiBhMgCpP]bBqA~AU`A", markers1)
//    var ride2 = RideHistoryItem("12.12.2222", "Chrzanow", "Krakow", "agqpHcovxB{DrPU`A{GgE[EA}L}@Sq@AeE@wJl@oLlAqCd@k@l@KjBzAlC`@nBo@`MkAlOGrCBn@sAjAS^CRA\\c@?WIcA~Jk@~ECVy@jIW@eDpAiD~BuPxPaDpAgAlAoA?]Aq@Ra@d@}CjDmBvBqBxBcCzBkG|@kBJg@@EPOj@uAxG]j@_E`BeC|AcCpBkAv@]NBZz@zH`B~Kf@zHId\\DlU~@xNzCf]nCn[h@`Le@|Ho@bDyFfSeB~GmC~HkJzXcH~MmEpHiJfSuFhN}AdBgGdEoBtAeC`DsBjDsA`FiAfFq@bDeBvHcElRoK~`@a@nBg@zFmCf^a@zG?vDv@tN^~BbAxBfEbCpB|AlDfFjGfL`C`FpBnFbFnPpGlTzFvPrCfHrHdPbOtW~P`ZpHjPlA~CjD|JfE|NlCdLrCbOdBnLtBjTdDv`@rBjX`Eli@fC|]tAlVn@j]Aha@?pWPxLbApS`CzTxGt^zEjZhAdMbA|VBxNOvKm@hOmAfNqAdKkBrKqCxLuBbHuJ`Wut@fgB_JdUcFvNuFjTkDfR{BfQuBnZo@dY@|Mj@vTx@pPhBv\\nElx@`Bv[x@|[C~PSnKoAd\\q@zZJpUlAtXlC|Y`G|f@bCn\\VtGd@|_@W~UWlIcBxXiDhZcChOeEzR_J`[uExNyHzWcIp_@w@lE}Gvg@eF`b@yGti@aLt~@{EhYiHxZwDjMuEjM}K~ViRt]mu@frAaf@zz@uIjOcKxRyFpMaHpRmF|Q{FhWi\\tkBgZheBiHld@cCzTqBpYcBng@{Bjx@aHleC{@v[[bYBrXh@l\\tB~d@bD~b@~SxkC`Bt[dAle@?pd@[nSmAp_@wCn~@kB~l@o@|d@i@d_BUjc@[jMs@fN}AzQsCnS_DhPaDzLmCpIgE~K{IxQwNrV_b@~r@s~@f}AwSt]kIhMwMnPmGrGsMjKuMjIuL~FsShJ_KbEiG|CcCfBiJpH_HrHeHdKuEtIeF`MyD|LkDdOuBfMuEl\\mD`WcE`ZwN~dAcQroAwEh_@_Dp[gBrX_Dhk@uBf^sChXgBnLiD~PeG~X{UhgA}Lxk@mK`f@eCvGqDzH{F`IkCbCyIbGwEjCoDpCuExFeDzF}D|HcG~HkG|HkB|CmBfB]^yFnAmMjD{MjDqL~CiCh@kBDyLsAmFGmFv@eEhBqF`DaDbAwBAeB[oAi@gC}B_@kBHk@b@e@p@PxAfC|@hE|AnJd@nFPlESzPa@~E_@nMi@zN]jNa@nEiBhMgCpP]bBqA~AU`A", markers1)
//    var ride3 = RideHistoryItem("12.12.2222", "Trzebinia", "Krakow", "agqpHcovxB{DrPU`A{GgE[EA}L}@Sq@AeE@wJl@oLlAqCd@k@l@KjBzAlC`@nBo@`MkAlOGrCBn@sAjAS^CRA\\c@?WIcA~Jk@~ECVy@jIW@eDpAiD~BuPxPaDpAgAlAoA?]Aq@Ra@d@}CjDmBvBqBxBcCzBkG|@kBJg@@EPOj@uAxG]j@_E`BeC|AcCpBkAv@]NBZz@zH`B~Kf@zHId\\DlU~@xNzCf]nCn[h@`Le@|Ho@bDyFfSeB~GmC~HkJzXcH~MmEpHiJfSuFhN}AdBgGdEoBtAeC`DsBjDsA`FiAfFq@bDeBvHcElRoK~`@a@nBg@zFmCf^a@zG?vDv@tN^~BbAxBfEbCpB|AlDfFjGfL`C`FpBnFbFnPpGlTzFvPrCfHrHdPbOtW~P`ZpHjPlA~CjD|JfE|NlCdLrCbOdBnLtBjTdDv`@rBjX`Eli@fC|]tAlVn@j]Aha@?pWPxLbApS`CzTxGt^zEjZhAdMbA|VBxNOvKm@hOmAfNqAdKkBrKqCxLuBbHuJ`Wut@fgB_JdUcFvNuFjTkDfR{BfQuBnZo@dY@|Mj@vTx@pPhBv\\nElx@`Bv[x@|[C~PSnKoAd\\q@zZJpUlAtXlC|Y`G|f@bCn\\VtGd@|_@W~UWlIcBxXiDhZcChOeEzR_J`[uExNyHzWcIp_@w@lE}Gvg@eF`b@yGti@aLt~@{EhYiHxZwDjMuEjM}K~ViRt]mu@frAaf@zz@uIjOcKxRyFpMaHpRmF|Q{FhWi\\tkBgZheBiHld@cCzTqBpYcBng@{Bjx@aHleC{@v[[bYBrXh@l\\tB~d@bD~b@~SxkC`Bt[dAle@?pd@[nSmAp_@wCn~@kB~l@o@|d@i@d_BUjc@[jMs@fN}AzQsCnS_DhPaDzLmCpIgE~K{IxQwNrV_b@~r@s~@f}AwSt]kIhMwMnPmGrGsMjKuMjIuL~FsShJ_KbEiG|CcCfBiJpH_HrHeHdKuEtIeF`MyD|LkDdOuBfMuEl\\mD`WcE`ZwN~dAcQroAwEh_@_Dp[gBrX_Dhk@uBf^sChXgBnLiD~PeG~X{UhgA}Lxk@mK`f@eCvGqDzH{F`IkCbCyIbGwEjCoDpCuExFeDzF}D|HcG~HkG|HkB|CmBfB]^yFnAmMjD{MjDqL~CiCh@kBDyLsAmFGmFv@eEhBqF`DaDbAwBAeB[oAi@gC}B_@kBHk@b@e@p@PxAfC|@hE|AnJd@nFPlESzPa@~E_@nMi@zN]jNa@nEiBhMgCpP]bBqA~AU`A", markers1)
//    var ride4 = RideHistoryItem("12.12.2222", "Poznan", "Krakow", "agqpHcovxB{DrPU`A{GgE[EA}L}@Sq@AeE@wJl@oLlAqCd@k@l@KjBzAlC`@nBo@`MkAlOGrCBn@sAjAS^CRA\\c@?WIcA~Jk@~ECVy@jIW@eDpAiD~BuPxPaDpAgAlAoA?]Aq@Ra@d@}CjDmBvBqBxBcCzBkG|@kBJg@@EPOj@uAxG]j@_E`BeC|AcCpBkAv@]NBZz@zH`B~Kf@zHId\\DlU~@xNzCf]nCn[h@`Le@|Ho@bDyFfSeB~GmC~HkJzXcH~MmEpHiJfSuFhN}AdBgGdEoBtAeC`DsBjDsA`FiAfFq@bDeBvHcElRoK~`@a@nBg@zFmCf^a@zG?vDv@tN^~BbAxBfEbCpB|AlDfFjGfL`C`FpBnFbFnPpGlTzFvPrCfHrHdPbOtW~P`ZpHjPlA~CjD|JfE|NlCdLrCbOdBnLtBjTdDv`@rBjX`Eli@fC|]tAlVn@j]Aha@?pWPxLbApS`CzTxGt^zEjZhAdMbA|VBxNOvKm@hOmAfNqAdKkBrKqCxLuBbHuJ`Wut@fgB_JdUcFvNuFjTkDfR{BfQuBnZo@dY@|Mj@vTx@pPhBv\\nElx@`Bv[x@|[C~PSnKoAd\\q@zZJpUlAtXlC|Y`G|f@bCn\\VtGd@|_@W~UWlIcBxXiDhZcChOeEzR_J`[uExNyHzWcIp_@w@lE}Gvg@eF`b@yGti@aLt~@{EhYiHxZwDjMuEjM}K~ViRt]mu@frAaf@zz@uIjOcKxRyFpMaHpRmF|Q{FhWi\\tkBgZheBiHld@cCzTqBpYcBng@{Bjx@aHleC{@v[[bYBrXh@l\\tB~d@bD~b@~SxkC`Bt[dAle@?pd@[nSmAp_@wCn~@kB~l@o@|d@i@d_BUjc@[jMs@fN}AzQsCnS_DhPaDzLmCpIgE~K{IxQwNrV_b@~r@s~@f}AwSt]kIhMwMnPmGrGsMjKuMjIuL~FsShJ_KbEiG|CcCfBiJpH_HrHeHdKuEtIeF`MyD|LkDdOuBfMuEl\\mD`WcE`ZwN~dAcQroAwEh_@_Dp[gBrX_Dhk@uBf^sChXgBnLiD~PeG~X{UhgA}Lxk@mK`f@eCvGqDzH{F`IkCbCyIbGwEjCoDpCuExFeDzF}D|HcG~HkG|HkB|CmBfB]^yFnAmMjD{MjDqL~CiCh@kBDyLsAmFGmFv@eEhBqF`DaDbAwBAeB[oAi@gC}B_@kBHk@b@e@p@PxAfC|@hE|AnJd@nFPlESzPa@~E_@nMi@zN]jNa@nEiBhMgCpP]bBqA~AU`A", markers1)
//     val _historyOfRidesList = arrayListOf<RideHistoryItem>(ride1,ride2,ride3,ride4)


}